/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerBarang;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelBarang;
import util.Koneksi;

/**
 *
 * @author user
 */
public class ViewBarang extends javax.swing.JFrame {

    Koneksi lisa = new Koneksi();
    ControllerBarang cb = new ControllerBarang();
    ModelBarang mb = new ModelBarang();
    /**
     * Creates new form ViewBarang
     */
    public ViewBarang() {
        initComponents();
        TampilData();
        setLocationRelativeTo(null);
    }
    private void bersih(){
        txtid.setText("");
        txtnama.setText("");
        txtjenis.setText("");
        txtjumlah.setText("");
        txtnama.requestFocus();
    }
    
    private void Baru(){
        btnbaru.setEnabled(false);
        btnsimpan.setEnabled(true);
        btnubah.setEnabled(false);
        btnhapus.setEnabled(false);
        txtid.setEditable(true);
        txtnama.setEditable(true);
        txtjenis.setEditable(true);
        txtjumlah.setEditable(true);
        bersih();
    }
    private void ubahDanhapus(){
        btnsimpan.setEnabled(true);
        txtnama.setEditable(true);
        txtjenis.setEditable(true);
        txtjumlah.setEditable(true);
        btnhapus.setEnabled(true);
        btnubah.setEnabled(true);
        bersih();
    }
    
    private void TampilData(){
        lisa.koneksiDatabase();

        DefaultTableModel tabelbrg = new DefaultTableModel();

        tabelbrg.addColumn("Id");
        tabelbrg.addColumn("Nama Barang");
        tabelbrg.addColumn("Jenis Barang");
        tabelbrg.addColumn("Jumlah Barang");

        tabelbarang.setModel(tabelbrg);
        try {
            String query = "select * from tbl_barang";

            ResultSet res = lisa.state.executeQuery(query);
            while (res.next()) {
                tabelbrg.addRow(new Object[]{
                    res.getString("Id"),
                    res.getString("Nama Barang"),
                    res.getString("Jenis Barang"),
                    res.getString("Jumlah Barang"),
                });
                tabelbarang.setModel(tabelbrg);

            }
        } catch (SQLException e) {
            System.err.println(""+e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnbaru = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtjenis = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        btnubah = new javax.swing.JButton();
        btnbersih = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id Barang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setText("Nama Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setText("Jenis Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel4.setText("Jumlah Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        btnbaru.setText("BARU");
        btnbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbaruActionPerformed(evt);
            }
        });
        getContentPane().add(btnbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 70, -1));

        txtid.setEnabled(false);
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, -1));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 140, -1));
        getContentPane().add(txtjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 140, -1));
        getContentPane().add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 140, -1));

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelbarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 590, 180));

        btnubah.setText("UBAH");
        btnubah.setEnabled(false);
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        getContentPane().add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 70, -1));

        btnbersih.setText("BERSIH");
        btnbersih.setEnabled(false);
        getContentPane().add(btnbersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 70, -1));

        btnsimpan.setText("SIMPAN");
        btnsimpan.setEnabled(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        btnhapus.setText("HAPUS");
        btnhapus.setEnabled(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 70, -1));

        btnclose.setText("TUTUP");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        
        try {
            String Nama = txtnama.getText();
            String Jenis = txtjenis.getText();
            int Jumlah = Integer.parseInt(txtjumlah.getText());
            
            mb.setNama(Nama);
            mb.setJenis(Jenis);
            mb.setJumlah(Jumlah);
            
            cb.simpanData(mb);
            TampilData();
            bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "HARAP MASUKAN DATA!!");
            txtnama.setText("");
            txtnama.requestFocus();
            
        }

    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        try {
            int Id = Integer.parseInt(txtid.getText().trim());
            String Nama = txtnama.getText().trim();
            String Jenis = txtjenis.getText().trim();
            int Jumlah = Integer.parseInt(txtjumlah.getText().trim());
            
            mb.setId(Id);
            mb.setNama(Nama);
            mb.setJenis(Jenis);
            mb.setJumlah(Jumlah);
            TampilData();
            bersih();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "SILAHKAN MASUKKAN DATA ANDA!!");
            System.err.println(""+e);
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            int Id = Integer.parseInt(txtid.getText());
            
            mb.setId(Id);
            cb.hapusData(mb);
            TampilData();
            bersih();
            
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "SILAHKAN MASUKKAN DATA ANDA!!");
            System.err.println(""+e);
            
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbaruActionPerformed
        // TODO add your handling code here:
        Baru();
    }//GEN-LAST:event_btnbaruActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void tabelbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbarangMouseClicked
        // TODO add your handling code here:
        ubahDanhapus();
        try {
            int baris = tabelbarang.getSelectedRow();
            txtid.setText(tabelbarang.getValueAt(baris, 0).toString());
            txtnama.setText(tabelbarang.getValueAt(baris, 1).toString());
            txtjenis.setText(tabelbarang.getValueAt(baris, 2).toString());
            txtjumlah.setText(tabelbarang.getValueAt(baris, 3).toString());
        } catch (Exception e) {
            System.err.println(""+e);
        }
    }//GEN-LAST:event_tabelbarangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbaru;
    private javax.swing.JButton btnbersih;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelbarang;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
