/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.xml.transform.Result;
import util.Koneksi;

/**
 *
 * @author user
 */
public class ViewCariBarang extends javax.swing.JFrame {
    Koneksi koneksi = new Koneksi();
    DefaultTableModel tabelcari = new DefaultTableModel();
    
    
    

    /**
     * Creates new form ViewCariBarang
     */
    public ViewCariBarang() {
        initComponents();
    }
    private void tampilData(){
        koneksi.koneksiDatabase();
        DefaultTableModel tabelsearch = new DefaultTableModel();

        tabelsearch.addColumn("Id");
        tabelsearch.addColumn("Nama Barang");
        tabelsearch.addColumn("Jenis Barang");
        tabelsearch.addColumn("Jumlah Barang");

        tabelcaridata.setModel(tabelsearch);
        try {
            String query = "select * from tbl_barang";

            ResultSet res = koneksi.state.executeQuery(query);
            while (res.next()) {
                tabelsearch.addRow(new Object[]{
                    res.getString("Id"),
                    res.getString("Nama Barang"),
                    res.getString("Jenis Barang"),
                    res.getString("Jumlah Barang"),
                });
                tabelcaridata.setModel(tabelsearch);

            }
        } catch (SQLException e) {
            System.err.println(""+e);
        }
    }

    public void searchData(){
        tabelcari.getDataVector().removeAllElements();
        try {
            koneksi.koneksiDatabase();
            String query = "select * from tbl_barang where nama like '%"+txtsearch.getText()+"%'";
            ResultSet res = koneksi.state.executeQuery(query);
            
            while (res.next()) {
                tabelcari.addRow(new Object[]{
                    res.getString("Id"),
                    res.getString("Nama Barang"),
                    res.getString("Jenis Barang"),
                    res.getString("Jumlah Barang")
                });
                tabelcaridata.setModel(tabelcari);
            }
        } catch (Exception e) {
            System.err.println(""+e);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelcaridata = new javax.swing.JTable();
        btncari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cari Barang  :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 150, -1));

        tabelcaridata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelcaridata);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 120));

        btncari.setText("Cari");
        getContentPane().add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        searchData();
        
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCariBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelcaridata;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
